-- backend/supabase/perf_hardening.sql — OPTIONAL performance hardening for the Supabase advisors.
-- Status: Section A (FK indexes) APPLIED 2026-06-26 as migration `perf_fk_indexes` (verified: 0 unindexed FKs remaining).
--         Section B (RLS init-plan rewrites) NOT APPLIED — these are ALTER POLICY (access-control) changes, intentionally
--         left for Cole to apply in the SQL editor; afterward re-run the two RLS test files named at the bottom.
--         (Re-running this whole file is safe: Section A is idempotent via IF NOT EXISTS.)
--
-- Two safe, behaviour-preserving sections:
--   A. Covering indexes for 30 unindexed foreign keys  (purely additive — clears `unindexed_foreign_keys`).
--   B. Wrap auth.uid() in a scalar subselect in 19 RLS policies (clears `auth_rls_initplan`).
--      `auth.uid()` and `(select auth.uid())` return the SAME value; only evaluation timing changes
--      (once per query instead of once per row). RLS semantics are IDENTICAL — generated by transforming
--      each policy's existing definition, not rewritten by hand.
--
-- NOT addressed here on purpose: `multiple_permissive_policies` (25 WARN). Those come from the intentional,
-- separately-auditable SELECT policies on game_card_instances / games / game_participants (e.g. the hidden-zone
-- owner policy vs. the public-zone policy vs. the revealed-peek policy). Merging them would silence the lint at
-- the cost of making the hidden-information boundary harder to audit — not worth it. Left as a deliberate choice.
--
-- AFTER APPLYING, re-run the hidden-info tests to confirm the model is intact:
--   tests/rls_assertions.sql   (SELECT path)   and   tests/rls_tamper_assertions.sql   (UPDATE-tamper path)

begin;

-- ── A. Foreign-key covering indexes (additive) — APPLIED 2026-06-26 (migration perf_fk_indexes) ──
create index if not exists idx_ai_coach_messages_deck_id on public.ai_coach_messages (deck_id);
create index if not exists idx_ai_coach_messages_owner_id on public.ai_coach_messages (owner_id);
create index if not exists idx_ai_deck_reviews_deck_id on public.ai_deck_reviews (deck_id);
create index if not exists idx_ai_deck_reviews_owner_id on public.ai_deck_reviews (owner_id);
create index if not exists idx_commander_damage_game_id on public.commander_damage (game_id);
create index if not exists idx_commander_damage_target_participant_id on public.commander_damage (target_participant_id);
create index if not exists idx_deck_cards_chosen_scryfall_id on public.deck_cards (chosen_scryfall_id);
create index if not exists idx_deck_cards_scryfall_id on public.deck_cards (scryfall_id);
create index if not exists idx_dice_rolls_actor_id on public.dice_rolls (actor_id);
create index if not exists idx_dice_rolls_game_id on public.dice_rolls (game_id);
create index if not exists idx_favorite_cards_scryfall_id on public.favorite_cards (scryfall_id);
create index if not exists idx_game_actions_actor_id on public.game_actions (actor_id);
create index if not exists idx_game_board_snapshots_game_id on public.game_board_snapshots (game_id);
create index if not exists idx_game_card_hidden_game_id on public.game_card_hidden (game_id);
create index if not exists idx_game_card_hidden_owner_participant_id on public.game_card_hidden (owner_participant_id);
create index if not exists idx_game_card_instances_attached_to on public.game_card_instances (attached_to);
create index if not exists idx_game_card_instances_controller_participant_id on public.game_card_instances (controller_participant_id);
create index if not exists idx_game_card_instances_scryfall_id on public.game_card_instances (scryfall_id);
create index if not exists idx_game_counters_game_id on public.game_counters (game_id);
create index if not exists idx_game_participants_player_profile_id on public.game_participants (player_profile_id);
create index if not exists idx_game_participants_profile_id on public.game_participants (profile_id);
create index if not exists idx_game_presets_owner_id on public.game_presets (owner_id);
create index if not exists idx_games_owner_id on public.games (owner_id);
create index if not exists idx_games_preset_id on public.games (preset_id);
create index if not exists idx_match_history_game_id on public.match_history (game_id);
create index if not exists idx_match_history_owner_id on public.match_history (owner_id);
create index if not exists idx_match_history_winner_participant_id on public.match_history (winner_participant_id);
create index if not exists idx_player_profiles_owner_id on public.player_profiles (owner_id);
create index if not exists idx_sync_events_game_id on public.sync_events (game_id);
create index if not exists idx_sync_events_user_id on public.sync_events (user_id);

-- ── B. auth_rls_initplan: wrap auth.uid() in a scalar subselect (identical semantics) — NOT YET APPLIED (Cole to apply) ──
alter policy "ai coach messages owned" on public.ai_coach_messages using (((select auth.uid()) = owner_id)) with check (((select auth.uid()) = owner_id));
alter policy "ai reviews owned" on public.ai_deck_reviews using (((select auth.uid()) = owner_id)) with check (((select auth.uid()) = owner_id));
alter policy "deck cards through owned deck" on public.deck_cards using ((EXISTS ( SELECT 1 FROM saved_decks d WHERE ((d.id = deck_cards.deck_id) AND (d.owner_id = (select auth.uid())))))) with check ((EXISTS ( SELECT 1 FROM saved_decks d WHERE ((d.id = deck_cards.deck_id) AND (d.owner_id = (select auth.uid()))))));
alter policy "favorite cards owned" on public.favorite_cards using (((select auth.uid()) = owner_id)) with check (((select auth.uid()) = owner_id));
alter policy "actions member append" on public.game_actions with check ((is_game_member(game_id) AND (actor_id = (select auth.uid()))));
alter policy "hidden owner only" on public.game_card_hidden using ((EXISTS ( SELECT 1 FROM game_participants p WHERE ((p.id = game_card_hidden.owner_participant_id) AND (p.profile_id = (select auth.uid())))))) with check ((EXISTS ( SELECT 1 FROM game_participants p WHERE ((p.id = game_card_hidden.owner_participant_id) AND (p.profile_id = (select auth.uid()))))));
alter policy "instances hidden zones owner" on public.game_card_instances using (((zone = ANY (ARRAY['hand'::text, 'library'::text])) AND (EXISTS ( SELECT 1 FROM game_participants p WHERE ((p.id = game_card_instances.owner_participant_id) AND (p.profile_id = (select auth.uid())))))));
alter policy "instances revealed peek" on public.game_card_instances using (((select auth.uid()) = ANY (revealed_to)));
alter policy "participants owner manage" on public.game_participants using ((EXISTS ( SELECT 1 FROM games g WHERE ((g.id = game_participants.game_id) AND (g.owner_id = (select auth.uid())))))) with check ((EXISTS ( SELECT 1 FROM games g WHERE ((g.id = game_participants.game_id) AND (g.owner_id = (select auth.uid()))))));
alter policy "participants self join" on public.game_participants with check ((profile_id = (select auth.uid())));
alter policy "participants self update" on public.game_participants using ((profile_id = (select auth.uid()))) with check ((profile_id = (select auth.uid())));
alter policy "presets owned" on public.game_presets using (((select auth.uid()) = owner_id)) with check (((select auth.uid()) = owner_id));
alter policy "games owner manage" on public.games using (((select auth.uid()) = owner_id)) with check (((select auth.uid()) = owner_id));
alter policy "history owned" on public.match_history using (((select auth.uid()) = owner_id)) with check (((select auth.uid()) = owner_id));
alter policy "player profiles owned" on public.player_profiles using (((select auth.uid()) = owner_id)) with check (((select auth.uid()) = owner_id));
alter policy "profiles own row" on public.profiles using (((select auth.uid()) = id)) with check (((select auth.uid()) = id));
alter policy "decks owned" on public.saved_decks using (((select auth.uid()) = owner_id)) with check (((select auth.uid()) = owner_id));
alter policy "sync events owned" on public.sync_events using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
alter policy "settings owned" on public.user_settings using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));

commit;
